[package]
name = "polywrap_client"
description = "Polywrap Client implementation in rust"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
polywrap_core.workspace = true
polywrap_msgpack.workspace = true
polywrap_client_builder.workspace = true
polywrap_resolvers.workspace = true
serde.workspace = true
serde_json.workspace = true
rmp-serde.workspace = true

[dev-dependencies]
polywrap_resolvers.workspace = true
polywrap_wasm.workspace = true
polywrap_tests_utils.workspace = true
wrap_manifest_schemas.workspace = true
polywrap_plugin = {path ="../plugin"}
num-bigint = { version = "0.4", default-features = false, features = ["serde"] }
bigdecimal = { version = "0.3.0", default-features = false, features = ["serde"] }
