[package]
name = "polywrap_msgpack"
version = "0.0.1-alpha.1"
license = "MIT"
description = "Todo"
edition = "2021"

[dependencies]
thiserror = "1.0.37"
rmp-serde = "1.1.1"
rmpv = "1.0.0"
serde = {version = "1.0.145", features = ["derive"]}