[package]
name = "polywrap_msgpack"
description = "Rust implementation of the WRAP msgpack encoding standard"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
polywrap_msgpack_serde = { git = "https://github.com/polywrap/msgpack-serde", branch = "namesty/wrap"}
serde_bytes = "0.11.9"