[package]
name = "polywrap_plugin_macro"
version = "0.0.1-alpha.1"
license = "MIT"
description = "Todo"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0.105", features=["full", "extra-traits"] }
polywrap_core = { path = "../core" }
polywrap_plugin = { path = "../plugin" }

[lib]
proc-macro = true

[dev-dependencies]
serde_json = "1.0.87"