[workspace]

members = [
    "packages/client",
    "packages/core",
    "packages/wasm",
    "packages/resolvers",
    "packages/msgpack",
    "packages/manifest",

    # Internal
    "packages/tests"
]