[package]
name = "polywrap_ffi_java_client"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["dylib"]

[dependencies]
polywrap_client.workspace = true
polywrap_core.workspace = true
polywrap_resolvers.workspace = true
polywrap_plugin.workspace = true
polywrap_msgpack.workspace = true
serde_json.workspace = true

fs_resolver_plugin = {path = "../plugins/fs-resolver"}
filesystem_plugin = {path = "../plugins/fs"}
http_resolver_plugin = {path = "../plugins/http-resolver"}
http_plugin = {path = "../plugins/http"}

jni = "0.20.0"
android_logger = "0.11"
log = "0.4.17"