[package]
name = "polywrap_client_default_config"
description = "Default configuration for Polywrap Client"
version = "0.1.6-beta.3"

edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde_json.workspace = true
serde.workspace = true
base64.workspace = true

polywrap_core = { version = "0.1.6-beta.1" }
polywrap_plugin = { version = "0.1.6-beta.1" }
polywrap_client_builder = { version = "0.1.6-beta.1" }
polywrap_msgpack = { version = "0.1.6-beta.1" }
polywrap_wasm = { version = "0.1.6-beta.1" }
wrap_manifest_schemas = { version = "0.1.6-beta.1" }

fs_plugin_rs = { version  = "0.0.1-beta.3" }
http_plugin_rs = { version  = "0.0.1-beta.3" }
