[package]
name = "polywrap_client_default_config"
description = "Default configuration for Polywrap Client"
version = "0.1.6-beta.5"

license = "MIT"
edition = "2021"
rust-version = "1.67"
repository = "https://github.com/polywrap/rust-client"

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.87"
base64 = "0.13.1"

polywrap_core = { version = "0.1.6-beta.5" }
polywrap_plugin = { version = "0.1.6-beta.5" }
polywrap_client_builder = { version = "0.1.6-beta.5" }
polywrap_msgpack = { version = "0.1.6-beta.5" }
polywrap_wasm = { version = "0.1.6-beta.5" }
polywrap_resolvers = { version = "0.1.6-beta.5" }
wrap_manifest_schemas = { version = "0.1.6-beta.5" }

polywrap_fs_plugin = { version  = "0.0.1-beta.2" }
polywrap_http_plugin = { version  = "0.0.1-beta.2" }

[workspace]