[package]
name = "polywrap_client_default_config"
description = "Default configuration for Polywrap Client"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde_json.workspace = true
serde.workspace = true
polywrap_core.workspace = true
polywrap_resolvers.workspace = true
polywrap_msgpack.workspace = true
polywrap_plugin.workspace = true
polywrap_client_builder.workspace = true
polywrap_wasm.workspace = true
wrap_manifest_schemas.workspace = true
base64.workspace = true

polywrap_fs_plugin = { version  = "0.0.1-beta.3" }
polywrap_http_plugin = { version  = "0.0.1-beta.3" }
