[package]
name = "polywrap_client_default_config"
description = "Default configuration for Polywrap Client"
version = "0.0.2"

edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde_json.workspace = true
serde.workspace = true
base64.workspace = true

polywrap_client = { version = "0.1.6-beta.1" }
fs_plugin_rs = { version  = "0.0.1-beta.2" }
http_plugin_rs = { version  = "0.0.1-beta.2" }