[package]
name = "polywrap_wasm"
description = "Rust implementation of WASM runtime compliant with WRAP standard"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
polywrap_core.workspace = true
wrap_manifest_schemas.workspace = true
polywrap_msgpack.workspace = true

serde.workspace = true
thiserror.workspace = true
serde_json.workspace = true
base64.workspace = true

wasmer = "3.1.1"
bytes = "1.4.0"

[dev-dependencies]
polywrap_tests_utils.workspace = true