[package]
name = "polywrap_wasm"
version = "0.0.1-alpha.1"
license = "MIT"
description = "Todo"
edition = "2021"

[dependencies]
wasmtime = "1.0.2"
rmp-serde = "1.1.1"
rmpv = "1.0.0"
serde = "1.0.145"
thiserror = "1.0.37"
async-trait = "0.1.57"
base64 = "0.13.0"
futures = "0.3.24"
serde_json = "1.0.87"
polywrap_core = {path = "../core"}
wrap_manifest_schemas = {path = "../manifest"}
polywrap_msgpack = {path = "../msgpack"}
polywrap_tests_utils = {path = "../tests-utils"}

[dev-dependencies]
tokio = { version = "1.3", features = ["full"] }