[package]
name = "polywrap_core"
description = "Core types of Polywrap client"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
regex.workspace = true
wrap_manifest_schemas.workspace = true
polywrap_msgpack.workspace = true
serde.workspace = true
jsonschema.workspace = true
serde_bytes.workspace = true
polywrap_uri.workspace = true
polywrap_core_macros = { workspace = true, optional = true }

[features]
default = ["macros"]

macros = ["polywrap_core_macros"]