[package]
name = "polywrap_core"
version = "0.0.1-alpha.1"
license = "MIT"
description = "Todo"
edition = "2021"

[dependencies]
thiserror = "1.0.37"
regex = "1.6.0"
async-trait = "0.1.57"
wrap_manifest_schemas = { path = "../manifest" }
polywrap_msgpack = { path = "../msgpack" }
serde = "1.0.145"
serde_json = "1.0.87"
jsonschema = "0.16.1"
rmp-serde = "1.1.1"
futures = "0.3.24"

[dev-dependencies]
mockall = "0.11.2"
