[package]
name = "polywrap_benchmarks"
description = "Polywrap Client benchmarks in rust"
version = "0.1.6-beta.5"
license = "MIT"
edition = "2021"
rust-version = "1.67"
repository = "https://github.com/polywrap/rust-client"

[lib]
crate-type = ["rlib"]
test = false

[dependencies]
polywrap_client = { version = "0.1.6-beta.5" }
polywrap_wasm = { version = "0.1.6-beta.5" }
polywrap_client_builder = { version = "0.1.6-beta.5" }
polywrap_core = { version = "0.1.6-beta.5" }
wrap_manifest_schemas = { version = "0.1.6-beta.5" }
polywrap_resolvers = { version = "0.1.6-beta.5" }
polywrap_msgpack = { version = "0.1.6-beta.5" }
polywrap_tests_utils = { version = "0.1.6-beta.5" }
polywrap_plugin = { version = "0.1.6-beta.5" }
polywrap_plugin_implementor = { version = "0.1.6-beta.5" }
polywrap_client_default_config = { version = "0.1.6-beta.5", path="../default-config" }

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "bench_invoke"
harness = false

[[bench]]
name = "bench_runtime"
harness = false

#[[bench]]
#name = "bench_load_wrapper"
#harness = false

[workspace]