[package]
name = "wrap_manifest_schemas"
description = "WRAP Manifest rust typings"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
polywrap_msgpack.workspace = true
serde.workspace = true
serde_json.workspace = true
jsonschema.workspace = true

semver = "1.0.14"
polywrap_schemafy = "0.1.1"
handlebars = "4.3.5"
polywrap-jsonref = "0.1.0"
ureq = "2.3.0"