[package]
name = "polywrap_manifest"
version = "0.0.1-alpha.1"
license = "MIT"
description = "Todo"
edition = "2021"

[dependencies]
thiserror = "1.0.37"
polywrap_msgpack = {path = "../msgpack"}
serde = {version = "1.0.145", features = ["derive"]}
serde_json = "1.0.87"
semver = "1.0.14"
jsonschema = "0.16.1"
rmp-serde = "1.1.1"
polywrap_schemafy = "0.1.1"

[build-dependencies]
thiserror = "1.0.37"
handlebars = "4.3.5"
semver = "1.0.14"
serde_json = "1.0.87"
polywrap-jsonref = "0.1.0"
serde = {version = "1.0.145", features = ["derive"]}
ureq = "2.3.0"