[package]
name = "polywrap_ffi_c"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
polywrap_client.workspace = true
polywrap_core.workspace = true
polywrap_resolvers.workspace = true
polywrap_plugin.workspace = true
polywrap_msgpack.workspace = true

serde_json.workspace = true

fs_resolver_plugin = {path = "../plugins/fs-resolver"}
filesystem_plugin = {path = "../plugins/fs"}
http_resolver_plugin = {path = "../plugins/http-resolver"}
http_plugin = {path = "../plugins/http"}

libc = "0.2"
