[package]
name = "polywrap_tests_utils"
description = "Utilities for testing Polywrap Client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
test = false

[dependencies]
polywrap_core.workspace = true
wrap_manifest_schemas.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
polywrap_plugin.workspace = true
polywrap_msgpack_serde.workspace = true
serde_bytes.workspace = true
tokio.workspace = true

reqwest = { version = "0.11", features = ["json"] }
zip = "0.6.4"
