[package]
name = "polywrap_tests_utils"
version = "0.0.1-alpha.1"
license = "MIT"
description = "Todo"
edition = "2021"

[lib]
test = false

[dependencies]
polywrap_core = { path = "../core" }
wrap_manifest_schemas = { path = "../manifest" }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.23.0", features = ["full"] }
zip = "0.6.4"
thiserror = "1.0"
polywrap_plugin = { path = "../plugin" }
polywrap_plugin_macro = { path = "../plugin_macro" }
polywrap_msgpack = { path = "../msgpack" }
serde = {version = "1.0.145", features = ["derive"]}
serde_json = "1.0.87"
