[package]
name = "polywrap_native"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
polywrap_client.workspace = true
polywrap_plugin.workspace = true
polywrap_wasm.workspace = true
polywrap_client_default_config.workspace = true
polywrap_msgpack_serde.workspace = true

thiserror.workspace = true
serde_json.workspace = true
serde.workspace = true

uniffi = { version = "0.24.2", features = [ "cli" ], default-features = false }

[build-dependencies]
uniffi = { version = "0.24.2", features = [ "build" ], default-features = false }

[dev-dependencies]
polywrap_tests_utils.workspace = true

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
