[package]
name = "polywrap_client_builder"
description = "Configuration builder for Polywrap Client"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
polywrap_core.workspace = true
polywrap_resolvers.workspace = true
serde_json.workspace = true
serde.workspace = true
polywrap_plugin.workspace = true
polywrap_wasm.workspace = true
base64.workspace = true

fs_resolver_plugin = {path = "../plugins/fs-resolver"}
filesystem_plugin = {path = "../plugins/fs"}
http_resolver_plugin = {path = "../plugins/http-resolver"}
http_plugin = {path = "../plugins/http"}

[dev-dependencies]
polywrap_tests_utils.workspace = true