[package]
name = "polywrap_client_builder"
description = "Configuration builder for Polywrap Client"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
polywrap_core.workspace = true
polywrap_resolvers.workspace = true
polywrap_resolver_extensions.workspace = true
polywrap_msgpack_serde.workspace = true
serde_json.workspace = true
serde.workspace = true

[dev-dependencies]
polywrap_tests_utils.workspace = true