[package]
name = "polywrap_resolvers"
version = "0.0.1-alpha.1"
license = "MIT"
description = "Todo"
edition = "2021"

[dependencies]
thiserror.workspace = true
regex.workspace = true
polywrap_core.workspace = true
polywrap_wasm.workspace = true
polywrap_msgpack.workspace = true
serde.workspace = true

pathdiff = "0.2.1"
