name: Rust Client

on:
  push: 
    branches:
      - main
      - develop
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1

      - name: Install grcov
        run: cargo install grcov

      - name: Instal llvm-tools
        run: rustup component add llvm-tools-preview

      - name: Generate test cases
        run: cargo run --package polywrap_tests_utils --bin generate 

      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests'

      - name: Get coverage
        run: grcov . -s . --binary-path ./target/debug -o ./cov.info --ignore */build/* --ignore */tests/* --ignore */wrap/* --ignore '*/tests-utils/*' --ignore-not-existing --branch

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          files: cov.info